# Generated by Django 4.1.10 on 2023-10-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0016_segmentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
