# Generated by Django 4.1.10 on 2023-11-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0016_segmentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="span",
            name="meta",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
