# Generated by Django 4.1.10 on 2023-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label_types", "0007_delete_relationtypeold"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytype",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="relationtype",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="spantype",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
